### PR TITLE
Model#encrypts: Allow custom type opjects to be supplied

### PR DESCRIPTION
**Pull request by FunkyloverOne**
Hey there!

This adds support for some custom types, like [store_model](https://github.com/DmitryTsepelev/store_model) gem for example, so you may have some subset of sensitive fields stored as an encrypted JSON in a single field, but it's more convenient to use than just a JSON or Hash.

The implementation could be better I believe, but it works :) It does not break any existing tests, and I didn't yet add any additional tests. Do you think I should add `store_model` as a development dependency and write tests that cover how those two work together?

Then we could state in README that `store_model` is also supported out of the box! :tada: 

---

P.S. That CI failure is strange, all the tests have successfully passed there.

### CODE REVIEW

**Comment by ankane** [comment]
Cleaning up stale PRs. Feel free to address the questions above and reopen.

**Comment by ankane** [comment]
Hey @FunkyloverOne, added support for custom types on master. If you have a chance to try it, let me know how it goes.

**Comment by FunkyloverOne** [comment]
@ankane I've just tried it, works as good as my fork, thanks for getting to it! :+1:

**Comment by ankane** [comment]
Awesome, thanks for confirming!

**Pull request closed without merging**
